### PR TITLE
Fix/scene changer singleton

### LINKED ISSUE #27: Make the SceneChanger make its GameObject be a singleton
Right now, if you change into a scene that has a Scene Changer GameObject, you'll keep your old Scene Changer and get the new one.  This is not useful.  There should be exactly 1 Scene Changer in the scene at any time.

### PR DESCRIPTION
**Pull request by fpdotmonkey**
If you run the tests in the test runner (Window>General>Test Runner, PlayMode>Run All), then everything should pass.  It's possible that TestSpacialGravityReceiver.TestMovesTowardCenterOfRegionOffAxis will fail, try running the tests again; apparently that test is inconsistent and it needs to be fixed (#32).

You can test interactively by opening the Title scene and navigating all around the different scenes.

Closes #27

### CODE REVIEW

File: Assets/Scripts/SceneManagement/SceneManifest.cs [hunk 1]
```diff
@@ -29,7 +31,9 @@ public static string Translate(SceneManifest scene)
         sceneNames.Add(SceneManifest.TestLevel, "testLevel");
         sceneNames.Add(SceneManifest.Title, "Title");
         sceneNames.Add(SceneManifest.Credits, "Credits");
-        sceneNames.Add(SceneManifest.DummyLevel, "DummyLevel");
+        sceneNames.Add(SceneManifest.DummyScene0, "DummyScene0");
+        sceneNames.Add(SceneManifest.DummyScene1, "DummyScene1");
+        sceneNames.Add(SceneManifest.SceneChanger, "SceneChanger");
```
Comment (cporter) [inline Assets/Scripts/SceneManagement/SceneManifest.cs]: This map should be static, and all of the adds to the map should be in a static code section. (See https://stackoverflow.com/questions/8459095/static-code-blocks). Basic principle is that if you *can* only do something once, only to it once.

**Review by cporter — CHANGES_REQUESTED** [review]
With the exception of you're doing a little extra work in creating that scene translation map multiple times, looks good. Clean that up and you're good to go.

**Review by cporter — APPROVED** [review]
